//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQToDataSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int MANV { get; set; }
        public int MACV { get; set; }
        public string TENNV { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
    }
}
